name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      # actions/checkout@v4.2.2
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false

      # taiki-e/install-action@v2.83.4
      - name: Install git-cliff
        uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b
        with:
          tool: git-cliff

      # Genereer de changelog
      - name: Generate Changelog
        run: git-cliff --config cliff.toml --latest --strip header -o NEW_CHANGELOG.md

      - name: Create Release
        run: |
          gh release create "$TAG_NAME" \
            --title "zbus-lockstep $TAG_NAME" \
            --notes-file NEW_CHANGELOG.md
        env:
          TAG_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
