name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history so git-cliff can generate the changelog

      # Installeer de kant-en-klare binary (veilig en Docker-vrij!)
      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      # Genereer de changelog via het normale commando:
      - name: Generate Changelog
        run: git-cliff --config cliff.toml --latest --strip header -o NEW_CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: NEW_CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
